In [1]:
import torch
from torch import nn as nn

### Given an input with (Nx, Ny) pixels (one channel), 

In [2]:
Nx = 2
Ny = 2
input = torch.ones(1,1,Nx,Ny)
print(input)

tensor([[[[1., 1.],
          [1., 1.]]]])


### a transpose convolution with one kernel of size (Kx,Ky), strides (Sx,Sy), and padding (Px,Py) 

In [3]:
Kx = 3
Ky = 3
Sx = 2
Sy = 2
Px = 0
Py = 0
T = nn.ConvTranspose2d(in_channels=1, out_channels=1, kernel_size=(Kx,Ky), stride=(Sx,Sy), padding=(Px,Py), bias = 0)
T.weight = nn.Parameter(torch.ones(1, 1, Kx, Ky))
print(T.weight)

Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)


### creates an output with (Ox,Oy) pixels such that Ox = (Nx-1)Sx+Kx-2Px and Ox = (Ny-1)Sy+Ky-2Py

In [4]:
output = T(input)
print(output)

tensor([[[[1., 1., 2., 1., 1.],
          [1., 1., 2., 1., 1.],
          [2., 2., 4., 2., 2.],
          [1., 1., 2., 1., 1.],
          [1., 1., 2., 1., 1.]]]], grad_fn=<ConvolutionBackward0>)
